import React, { useState } from 'react';
import { CheckCircle, XCircle, FileText } from 'lucide-react';
import { claims } from '../data/claims';
import { formatCurrency } from '../lib/utils';
import { RiskBadge } from '../components/ui/Badge';

const verificationClaims = claims.filter(claim => claim.riskScore >= 60);
type Decision = 'disetujui' | 'ditolak';

export function Verification() {
  const [decisions, setDecisions] = useState<Record<string, Decision>>({});
  const pending = verificationClaims.filter(claim => !decisions[claim.id]);
  const decide = (id: string, decision: Decision) => setDecisions(current => ({ ...current, [id]: decision }));
  return <div className="p-6 max-w-[1600px] mx-auto"><div className="mb-6"><h2 className="text-2xl font-bold">Pusat Verifikasi</h2><p className="mt-1.5 text-sm text-slate-500">Tinjau bukti dan ambil keputusan atas klaim dengan risiko tinggi.</p></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6"><Metric label="Menunggu Verifikasi" value={pending.length.toString()} color="text-orange-600" /><Metric label="Disetujui" value={Object.values(decisions).filter(value => value === 'disetujui').length.toString()} color="text-emerald-600" /><Metric label="Ditolak" value={Object.values(decisions).filter(value => value === 'ditolak').length.toString()} color="text-red-600" /></div><div className="space-y-4">{verificationClaims.map(claim => { const decision = decisions[claim.id]; return <div key={claim.id} className="card p-5 flex flex-col lg:flex-row gap-5 lg:items-center"><div className="w-11 h-11 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center flex-shrink-0"><FileText size={21} /></div><div className="flex-1"><div className="flex flex-wrap gap-2 items-center"><h3 className="font-semibold">{claim.id}</h3><RiskBadge level={claim.riskLevel} /></div><p className="mt-1 text-sm text-slate-600">{claim.patientName} · {claim.providerName}</p><p className="mt-1 text-xs text-slate-400">{claim.diagnosisCode} · {formatCurrency(claim.amount)} · Skor risiko {claim.riskScore}/100</p><div className="mt-3 flex flex-wrap gap-2">{claim.anomalyFlags.map(flag => <span key={flag} className="px-2 py-1 rounded text-xs bg-orange-50 text-orange-700">{flag.replace('_', ' ')}</span>)}</div></div>{decision ? <span className={`inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-semibold ${decision === 'disetujui' ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'}`}>{decision === 'disetujui' ? <CheckCircle size={16} /> : <XCircle size={16} />}{decision === 'disetujui' ? 'Klaim Disetujui' : 'Klaim Ditolak'}</span> : <div className="flex gap-2"><button onClick={() => decide(claim.id, 'disetujui')} className="px-3 py-2 rounded-lg text-sm font-semibold bg-green-600 hover:bg-green-700 text-white">Setujui</button><button onClick={() => decide(claim.id, 'ditolak')} className="px-3 py-2 rounded-lg text-sm font-semibold bg-white border border-red-200 hover:bg-red-50 text-red-700">Tolak</button></div>}</div>; })}</div></div>;
}
function Metric({ label, value, color }: { label: string; value: string; color: string }) { return <div className="card p-4"><p className="text-xs text-slate-500">{label}</p><p className={`mt-1 text-2xl font-bold ${color}`}>{value}</p></div>; }
